name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'DevExpress/devextreme-reactive'
    - name: Upgrade yarn
      run: yarn policies set-version
    - name: Run yarn
      run: yarn install
    - name: Build sources
      run: yarn build
